package com.gchess

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.server.testing.*
import java.io.File

/**
 * Generates OpenAPI specification from the application routes.
 * Uses Kompendium to automatically generate the spec based on NotarizedRoute annotations.
 * This is executed as part of the build process to create a static openapi.json file.
 */
fun main(args: Array<String>) {
    if (args.isEmpty()) {
        error("Usage: GenerateOpenApiSpec <output-file-path>")
    }

    val outputPath = args[0]
    val outputFile = File(outputPath)

    // Start the application in test mode and fetch the generated OpenAPI spec
    testApplication {
        // module() is automatically called from application.conf
        // (see ktor.application.modules in application.conf)

        val client = createClient {
            // No additional configuration needed
        }

        // Fetch the OpenAPI spec from the /openapi.json endpoint (generated by Kompendium)
        val response = client.get("/openapi.json")
        val openApiJson = response.bodyAsText()

        // Write to file
        outputFile.writeText(openApiJson)

        println("Successfully generated OpenAPI spec (${openApiJson.length} bytes)")
    }
}
