package com.gchess

import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import com.gchess.chess.infrastructure.adapter.driver.configureGameRoutes
import com.gchess.infrastructure.config.JwtConfig
import com.gchess.infrastructure.config.OpenApiConfig
import com.gchess.infrastructure.config.appModule
import com.gchess.user.infrastructure.adapter.driver.configureAuthRoutes
import com.gchess.user.infrastructure.adapter.driver.configureUserRoutes
import io.bkbn.kompendium.core.plugin.NotarizedApplication
import io.bkbn.kompendium.oas.OpenApiSpec
import io.bkbn.kompendium.oas.info.Contact
import io.bkbn.kompendium.oas.info.Info
import io.bkbn.kompendium.oas.server.Server
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.auth.jwt.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.plugins.contentnegotiation.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import kotlinx.serialization.json.Json
import org.koin.ktor.plugin.Koin
import org.koin.logger.slf4jLogger
import java.net.URI

fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
        module()
    }.start(wait = true)
}

fun Application.module() {
    // Koin dependency injection
    install(Koin) {
        slf4jLogger()
        modules(appModule)
    }

    // Content negotiation for JSON
    install(ContentNegotiation) {
        json(Json {
            prettyPrint = true
            isLenient = true
            ignoreUnknownKeys = true
        })
    }

    // OpenAPI Documentation
    install(NotarizedApplication()) {
        spec = OpenApiSpec(
            info = Info(
                title = OpenApiConfig.TITLE,
                version = OpenApiConfig.VERSION,
                description = OpenApiConfig.DESCRIPTION.trimIndent(),
                contact = Contact(
                    name = OpenApiConfig.Contact.NAME,
                    email = OpenApiConfig.Contact.EMAIL
                )
            ),
            servers = mutableListOf(
                Server(
                    url = URI(OpenApiConfig.Server.LOCAL_URL),
                    description = OpenApiConfig.Server.LOCAL_DESCRIPTION
                )
            )
        )
    }

    // JWT Authentication
    install(Authentication) {
        jwt("jwt-auth") {
            realm = JwtConfig.REALM
            verifier(JwtConfig.makeVerifier())
            validate { credential ->
                // Validate that the token has a playerId claim
                if (credential.payload.getClaim("playerId").asString() != null) {
                    JWTPrincipal(credential.payload)
                } else {
                    null
                }
            }
        }
    }

    // Configure routes
    configureGameRoutes()  // Chess context routes (will be protected with JWT)
    configureAuthRoutes()  // User context auth routes (register, login) - public
    configureUserRoutes()  // User context user routes (get user)

    routing {
        get("/") {
            call.respondText("gChess API is running!")
        }

        // OpenAPI spec is available at:
        // - /openapi.json (dynamic, generated by Kompendium)
        // - A static copy is also generated at build time in src/main/resources/openapi/openapi.json
        // To view with Swagger UI, visit https://petstore.swagger.io/ and load http://localhost:8080/openapi.json
    }
}
